apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs_share2
    server: 10.0.0.1
